### PR TITLE
Organized imports and fixed warnings

### PR DESCRIPTION
**Pull request by TikhonJelvis**
Cleaned up imports:
- Moved all the helper modules into `Slick` namespace. This way it's easier to see which ones are part of the project, which was a bit confusing when I started reading the code.
- Made imports as explicit as possible by either importing things qualified or using explicit import lists. This future-proofs the code a bit and makes it easier to follow for people unfamiliar with GHC's API (ie me)
- Restyled all the imports with [stylish-haskell](https://github.com/jaspervdj/stylish-haskell). The resulting style is slightly weird, but I've found it much easier to read once I got used to it.

Fixed warnings from `-Wall`:
- A few incomplete pattern matches got explicit calls to `error`.
- Added top-level type signatures everywhere they were missing.
  - In a couple of cases, this required additional extensions which,I believe, would have been needed anyhow with GHC 7.10. (See GHC 7.10's [changelog](https://downloads.haskell.org/~ghc/7.10.1-rc1/docs/html/users_guide/release-7-10-1.html#idp5770992).)
- A bunch of other misc changes.

None of this should change how the code works, it should just make the code cleaner and more maintainable. 

Also, I ignored a couple of warnings I don't care about, namely name shadowing and unused values in do blocks.

### CODE REVIEW

**Comment by imeckler** [comment]
Is it possible to merge some of the changes? Specifically I prefer to import all the constructors of HsExpr and related types rather than qualifying them as in https://github.com/imeckler/auto/pull/2/files#diff-20653f385fb8dd1f9dafae189082442bL210.

**Comment by TikhonJelvis** [comment]
Oh yeah, I can change that this evening.

**Comment by TikhonJelvis** [comment]
Okay, I made the changes you mentioned and merged in your latest changes with mine.

**Comment by imeckler** [comment]
Thanks, just merged all this stuff in manually.

**Pull request closed without merging**
